language: python
# python versions to use during the tests
python:
    - "3.7"
before_install:
  - pip install -U pip
  - pip install -U pytest
install:
    - pip install .
# command to run tests
script:
  - pytest tests
